tasks:
  - name: setup and build
    init: >
      bundle install &&
      gp sync-done bundle
    command: jekyll build --watch

  - name: dev server
    init: gp sync-await bundle
    command: jekyll serve
