# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: setup
    init: |
      bundle install
      gp sync-done bundle

  - name: build & watch
    init: gp sync-await bundle
    command: jekyll build --watch

  - name: dev server
    init: gp sync-await bundle
    command: jekyll serve

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
